CREATE DATABASE IF NOT EXISTS db_exemplo;

USE db_exemplo;

CREATE TABLE IF NOT EXISTS Cliente (

    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS Produto (

    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estoque INT NOT NULL DEFAULT 0,
    preco DOUBLE NOT NULL DEFAULT 0.00

);

SHOW TABLES;